### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Maricbrass** [sudofox/minecraft-alt-manager#1]
I don't understand how and from where we have to start

**Comment by sudofox** [comment]
For starters: this is a bit outdated and probably needs to be updated since there's been lots of changes to how Mojang/Microsoft auth works. This was originally written in order to reuse tokens when I was working on testing a Minecraft bot and was having issues with getting ratelimited by Mojang for constantly re-authing. I'm not sure if I'll bother updating it since I've learned a lot more since then; if I do I'll probably entirely re-implement it with node.js and the prismarine-related libraries since they're actively maintained (instead of manual HTTP calls with some odd PHP scripts)

So, if you still want to muck about with it, you'd want to create the sqlite3 database from the schema file, then use the scripts to add accounts. After that you can load up the sqlite3 database in whatever thing you need to use the tokens for and pull the data from that. It will only work with non-migrated (non-Microsoft) accounts.

There's most likely better tools out there at this point, so I'd look for those. Feel free to study this for ideas on how to implement your thing though. Hope that helps!
